### ISSUE TITLE
Lecture slides and notes format

### ISSUE THREAD

**Issue by 7vik** [Atharva-Chandak/orca_web_template#1]
Is it possible to have a flexible file format for lecture slides, notes, etc? @Atharva-Chandak

**Comment by Atharva-Chandak** [comment]
In the recent versions, it has already been incorporated. 
For correcting in previous versions, just remove ".pdf" extension (wherever present) in 'href' attribute of the < a> tags of "resources.html" file and add the appropriate extension in file name itself for the keys 'link' present in file "_data>resources>assign.yml" or "_data>resources>lectures.yml".
