### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by twitu** [Atharva-Chandak/orca_web_template#2]
1. [karan/joe](https://github.com/karan/joe) is has an excellent README. You can pick a few sub-headings of it.
2. use markdown supported numbered bullets like `1.` instead of `1]`. You can refer the markdown syntax give [here](https://guides.github.com/features/mastering-markdown/).
3. Since this repository is a template people don't need to fork it, they could instead use the template. You can read about templates [here](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)
4. `code highlight` directories, html tags or anything that is directly named in the repository, it indicates that this element is part of the source code in some way. Again check the markdown syntax guide for what is possible.

**Comment by 7vik** [comment]
@Atharva-Chandak Any updates with this?
