### ISSUE TITLE
Even better README

### ISSUE THREAD

**Issue by twitu** [Atharva-Chandak/orca_web_template#5]
The README is better off with #2 solved. Here's some more information you can add,

1. You can put the [hosted template](https://atharva-chandak.github.io/orca_web_template/) link, at the very top of the page in the description of the repository.

2. > No need to code the messy HTML pages. Just make a few changes in user-friendly syntax, and you'll be good to go.

     I feel this point should be at the very top. It's the most important reason to use a jekyll template for a course website

3. > 4. Adding data in .yml files

   You can link the names of specific .yml files that need to be change the contents of a particular page . As an example, `lectures.yml` for the `Resources` page, if I remember correctly, kind of like a tutorial cum guide.

4. You can mention the p-paf website under a separate sub-heading as `Template used in`. This is will bring attention to the fact that the template is being used and also allow you to add more websites later.

P.S. I hope you've checked that the use template option automatically handles the changes to the URL of the website, so there isn't a problem like the one we had earlier with PPAF.

P.P.S. You can't merge testing branch with master because they have all the same commits, no difference at all.

**Comment by twitu** [comment]
A small tip when you make a commit that resolves an issue just write `closes #5` in the commit message, it links that commit with this issue and makes it easy to track changes.

You can read more about this at https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords.

**Comment by Atharva-Chandak** [comment]
Alright, will do that from now on. Thanks for the tip!
